[package]
name = "sandbox-rust-hello-world"
version = "0.1.0"
authors = ["kamataryo <mugil.cephalus+github.com@gmail.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "sandbox-rust-hello-world"
path = "src/main.rs"
